stages:
  - dev
  - staging
  - production

##
## Child pipeline
## Job: Terraform main pipeline: Init, validate, fmt, plan and apply
## Env: Dev
##
terraform-dev:
  stage: dev
  variables:
    TF_ENV_PATH: terraform/projectA/dev
    AWS_DEFAULT_REGION: eu-central-1
  trigger:
    include:
      - project: 'aws-terraform4/templates/cicd'
        ref: main
        file: 'terraform.gitlab-ci.yml'
    strategy: depend